In [ ]:
#MINE UNIT DATA

In [54]:
from selenium import webdriver
#from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from time import sleep
import pandas as pd
import re
import datetime
options = Options()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
#options.add_argument("window-size=1400,600")
#options.add_argument('--disable-gpu')  # Last I checked this was necessary.
#page= driver.execute_script("return document.body.innerHTML")

#____________________________________________________________________________________
def rL(pL):
    #full time resultss
    
    k1=pL[0]+pL[1]
    v1=float(pL[2])
    
    k2=pL[0]+pL[3]
    v2=float(pL[4])
    
    k3=pL[0]+pL[5]
    v3=float(pL[6])
    #half time rwsults
    k11=pL[7]+pL[8]
    v11=float(pL[9])
    
    k22=pL[7]+pL[10]
    v22=float(pL[11])
    
    k33=pL[7]+pL[12]
    v33=float(pL[13])
    
    kov05=pL[14]+pL[15]
    if kov05=='Total goals (0.5)over':
         #over/Under 0.5
        von05=float(pL[16])

        kuv05=pL[14]+pL[17]
        vun05=float(pL[18])

        #over 1.5
        kov25=pL[19]+pL[20]
        von25=float(pL[21])

        kuv25=pL[19]+pL[22]
        vun25=float(pL[23])

        #over 2.5
        kov35=pL[24]+pL[25]
        von35=float(pL[26])

        kuv35=pL[24]+pL[27]
        vun35=float(pL[28])
        
        #over 3.5
        kov45='Total goals (2.5)over'
        von45=0

        kuv45='Total goals (3.5)under'
        vun45=0

        #over 4.5
        kov55='Total goals (4.5)over'
        von55=0

        kuv55='Total goals (4.5)under'
        vun55=0
    elif kov05=='Total goals (1.5)over':
        #over/Under 0.5
        kov05='Total goals (0.5)over'
        von05=0

        kuv05='Total goals (0.5)under'
        vun05=0
        
         #over/Under 1.5
        kov25=pL[14]+pL[15]
        von25=float(pL[16])

        kuv25=pL[14]+pL[17]
        vun25=float(pL[18])

        #over 2.5
        kov35=pL[19]+pL[20]
        von35=float(pL[21])

        kuv35=pL[19]+pL[22]
        vun35=float(pL[23])

        #over 3.5
        kov45=pL[24]+pL[25]
        von45=float(pL[26])

        kuv45=pL[24]+pL[27]
        vun45=float(pL[28])
        
        #over 4.5
        kov55='Total goals (4.5)over'
        von55=0

        kuv55='Total goals (4.5)under'
        vun55=0
      
    elif kov05=='Total goals (2.5)over':
        #over/Under 0.5
        kov05='Total goals (0.5)over'
        von05=0

        kuv05='Total goals (0.5)under'
        vun05=0
        
        #over/Under 1.5
        kov25='Total goals (1.5)over'
        von25=0

        kuv25='Total goals (1.5)under'
        vun25=0
        
         #over/Under 2.5
        kov35=pL[14]+pL[15]
        von35=float(pL[16])

        kuv35=pL[14]+pL[17]
        vun35=float(pL[18])

        #over 3.5
        kov45=pL[19]+pL[20]
        von45=float(pL[21])

        kuv45=pL[19]+pL[22]
        vun45=float(pL[23])

        #over 4.5
        kov55=pL[24]+pL[25]
        von55=float(pL[26])

        kuv55=pL[24]+pL[27]
        vun55=float(pL[28])
        
          
   # First to Score
    fk11=pL[50]+pL[51]
    fv11=float(pL[52])
    
    fk22=pL[50]+pL[53]
    fv22=float(pL[54])
    
    fk33=pL[50]+pL[55]
    fv33=float(pL[56])
    tName='TIME'
    tValue=pL[-2]
    tmName='TEAMS'
    tmValue=pL[-1]

    T2='tIMEsTAMP2'
    d2=datetime.datetime.now().strftime('%d/%m/%Y %a %H:%M')

    RK='ALL RECORDS'
    RV=pL[:]
    rDic={k1:v1,k2:v2,k3:v3,k11:v11,k22:v22,k33:v33,kov05:von05,kuv05:vun05,kov25:von25,kuv25:vun25,kov25:von25,
          kuv35:vun35,kov35:von35,kuv45:vun45,kov45:von45,kuv55:vun55,kov55:von55,fk11:fv11,fk22:fv22,fk33:fv33
          ,tName:tValue,tmName:tmValue,T2:d2}
    rDic2={RK:RV}
   
    return rDic,rDic2


#____________________________________________________________________________________________
def countD(n,str1="Next job in {} seconds"):
    countDown = n
    while (countDown >= 0):
        cc=[]
        if countDown != 0:
            cc.append(countDown)
            print(str1.format(cc[0]),end='\r')
            sleep(1)
            cc.clear()
            countDown = countDown - 1
        else:
            break

            



def lData(pageSource,driver):
    try:
        
        table = pd.read_html(pageSource)
        fList=[]
        fList2=[]
        for n in range(0,15,2):
            x=[table[0].iloc[:, 0][n],table[0].iloc[:, 1][n]]
            y=(table[0].iloc[:, 0][n+1])
            String1=y.replace(',','.')
            revString1 = re.sub(r'\s\s', ",", String1).split(",")
            Rev=revString1+x
            d,d2=rL(Rev)
            fList.append(d)
         

        dF=pd.DataFrame(fList)
      
        
        DF=dF.fillna(0)  
        
     
        with open('/home/gsociety/Desktop/The Model/STORAGE/PREDICT/liveDataPRE.csv', 'a') as f:
            DF.to_csv(f, index=False, header=False)
        #del fList[:]
        fList.clear()
      
        #del fList[:]
        fList.clear()
    
        print('Data saving DONE!....',end='\r')
        driver.close()
        
    except:
        countD(10,'Failed! Retrying  in {}  seconds')
        #print('Failed! Retrying in {}  seconds'.format(cc[0]),end='\r')
        driver.close()
        sleep(3)
        reload()

def reload():
        print('loading page...',end='\r')
        sleep(2)
        driver = webdriver.Chrome(executable_path="/home/gsociety/Desktop/solen/chromedriver")#,chrome_options=options)
        
        driver.get("https://www.mozzartbet.co.ke/en/virtual-games/vfl")
        sleep(3)
        print('Loading complete!    ',end='\r')
        pageSource=(driver.page_source).encode('utf-8')
        sleep(2)
        lData(pageSource,driver)
       
        

In [55]:

print('MINING DATA NUMBER:')

#options = Options()
#options.add_argument('--headless')


try:
    reload()

except:   
    print('ERR')
    pass


MINING DATA NUMBER:


In [3]:
#######SAVE UNIT DATA TO PREDICT
import pandas as pd

In [4]:
#df= pd.read_csv('/home/gsociety/Desktop/The Model/STORAGE/ANALIZ/liveDataG5.csv')
df= pd.read_csv('/home/gsociety/Desktop/The Model/STORAGE/PREDICT/liveDataPRE.csv')


df.head()

1     2     X   HT1   HT2   HTX  FS (0:0)  FS(0:0)2  FS(0:0)X  \
0  5.00  1.65  3.95  5.50  2.00  2.50      3.00      1.50     10.50   
1  3.65  1.85  4.30  3.50  2.30  2.75      2.20      1.65     28.00   
2  5.25  1.75  3.50  5.25  2.10  2.45      3.00      1.55     10.25   
3  1.70  4.30  4.30  2.00  4.35  2.85      1.55      2.55     24.00   
4  5.75  1.65  3.85  5.75  1.95  2.55      3.30      1.45     10.25   

                      TEAMSd          ...          G(0.5)U  G(1.5)O  G(1.5)U  \
0     VFL ANKARA  VFL BERLIN          ...              0.0     1.35     3.05   
1  VFL STOCKHOLM  VFL LONDON          ...              0.0     0.00     0.00   
2         VFL BERN  VFL OSLO          ...              0.0     1.30     3.10   
3        VFL ROME  VFL PARIS          ...              0.0     0.00     0.00   
4  VFL VIENNA  VFL AMSTERDAM          ...              0.0     1.50     2.45   

   G(2.5)O  G(2.5)U  G(3.5)O  G(3.5)U  G(4.5)O  G(4.5)U             timestamp  
0     2.10     1.65     3.85     1.22     0.00     0.00  08/09/2018 Sat 10:42  
1     1.50     2.45     2.40     1.50     4.20     1.18  08/09/2018 Sat 10:42  
2     2.00     1.75     3.40     1.30     0.00     0.00  08/09/2018 Sat 10:42  
3     1.55     2.30     2.40     1.50     3.95     1.20  08/09/2018 Sat 10:42  
4     2.45     1.50     4.30     1.18     0.00     0.00  08/09/2018 Sat 10:42  

[5 rows x 22 columns]

In [5]:
def teamCoded(S):
    
    cats=['MADRID', 'AMSTERDAM','BERLIN','LONDON','ROME','OSLO','LISBON','PARIS','BRUSSELS','ATHENS','STOCKHOLM',
          'COPENHAGEN','VIENNA', 'ANKARA','EDINBURGH','BERN']

    catsRev=[]
    for tm in S:
        if tm == cats[0]:
            catsRev.append(1)
        elif tm == cats[1]:
            catsRev.append(2)
        elif tm == cats[2]:
            catsRev.append(3)
        elif tm == cats[3]:
            catsRev.append(4)
        elif tm == cats[4]:
            catsRev.append(5)
        elif tm == cats[5]:
            catsRev.append(6)
        elif tm == cats[6]:
            catsRev.append(7)
        elif tm == cats[7]:
            catsRev.append(8)
        elif tm == cats[8]:
            catsRev.append(9)
        elif tm == cats[9]:
            catsRev.append(10)
        elif tm == cats[10]:
            catsRev.append(11)
        elif tm == cats[11]:
            catsRev.append(12)
        elif tm == cats[12]:
            catsRev.append(13)
        elif tm == cats[13]:
            catsRev.append(14)
        elif tm == cats[14]:
            catsRev.append(15)
        elif tm == cats[15]:
            catsRev.append(16)
    return catsRev

#funxion to input(ps) DF column of form/content (3:2) eg HT result or HT results and out put ps.series with eithe 0,1 or 2
def results(ps):
    lp=[]
    for x in ps:
        h=x.replace(':','  ')[:1]
        a=x.replace(':','  ')[1:]
        if float(h) > float(a):
            lp.append(1)

        elif float(a) > float(h):
            lp.append(2)
        else:
            lp.append(0)

    return pd.Series(lp)



def over_under(ps,n):
    lp=[]
    for x in ps:
        h=x.replace(':','  ')[:1]
        a=x.replace(':','  ')[1:]
        # if goals sum is greater than n value is 1
        
        if (float(h) + float(a)) > float(n):
            lp.append(1)

        else:
            #means it is under n eg under 2.5
            lp.append(0)

    return pd.Series(lp)

In [6]:
#split TEAMS into HOME & AWAY 
df['HOME']=pd.Series([x.split()[1] for x in df.TEAMSd])
df['AWAY']=pd.Series([x.split()[3] for x in df.TEAMSd])
df['TIMEdd']=pd.Series([x.split()[1] for x in df.TIMED])
df['TIMEst']=pd.Series([x.split()[0] for x in df.timestamp])
df['TIMEfc']=pd.Series([p[3:][5:8]+p[2:][:4]+p[:][:2] for p in df.TIMEst])
#df['TIMEddR']=pd.Series([x.split()[1] for x in df.TIMEDdd])

lx=[]
for x in df.TIMED:
    p=x.split()[1].replace(':','.')
    if float(p)> 1.00:
        q=('0'+str((round((float(p.replace(':','.'))-1),2))).replace('.',':')+'0')[:5]
    
    else:
        p=float(p)+24.00
        q=str((float(str(p).replace(':','.'))-1)).replace('.',':') 
    lx.append(q)
    
    
df['TIMEr']=pd.Series(lx)

df['TIMER']=df['TIMEfc']  + ' ' + df['TIMEdd']


#Use teamCode FX to code HOME & AWAY collumns and crean new HOMECODE & AWAYCODE
df['HOMECODE']=teamCoded(df['HOME'])
df['AWAYCODE']=teamCoded(df['AWAY'])
#df['TEAMSC']=df['HOMECODE'] + df['AWAYCODE']
df['TC']=df['HOME']+' '+df['AWAY']
colum=['TC','HOMECODE', 'AWAYCODE','TIMER','TIMED','TIMEr',
'1', '2', 'X', 'HT1', 'HT2', 'HTX', 'FS (0:0)', 'FS(0:0)2', 'FS(0:0)X',
        'G(0.5)O', 'G(0.5)U', 'G(1.5)O', 'G(1.5)U', 'G(2.5)O',
       'G(2.5)U', 'G(3.5)O', 'G(3.5)U', 'G(4.5)O', 'G(4.5)U']
data=df.reindex(columns=colum).fillna(0)

data.head()

TC  HOMECODE  AWAYCODE           TIMER      TIMED  TIMEr  \
0     ANKARA BERLIN        14         3  18/09/08 10:47  Sat 10:47  09:47   
1  STOCKHOLM LONDON        11         4  18/09/08 10:47  Sat 10:47  09:47   
2         BERN OSLO        16         6  18/09/08 10:47  Sat 10:47  09:47   
3        ROME PARIS         5         8  18/09/08 10:47  Sat 10:47  09:47   
4  VIENNA AMSTERDAM        13         2  18/09/08 10:47  Sat 10:47  09:47   

      1     2     X   HT1   ...     G(0.5)O  G(0.5)U  G(1.5)O  G(1.5)U  \
0  5.00  1.65  3.95  5.50   ...         0.0      0.0     1.35     3.05   
1  3.65  1.85  4.30  3.50   ...         0.0      0.0     0.00     0.00   
2  5.25  1.75  3.50  5.25   ...         0.0      0.0     1.30     3.10   
3  1.70  4.30  4.30  2.00   ...         0.0      0.0     0.00     0.00   
4  5.75  1.65  3.85  5.75   ...         0.0      0.0     1.50     2.45   

   G(2.5)O  G(2.5)U  G(3.5)O  G(3.5)U  G(4.5)O  G(4.5)U  
0     2.10     1.65     3.85     1.22     0.00     0.00  
1     1.50     2.45     2.40     1.50     4.20     1.18  
2     2.00     1.75     3.40     1.30     0.00     0.00  
3     1.55     2.30     2.40     1.50     3.95     1.20  
4     2.45     1.50     4.30     1.18     0.00     0.00  

[5 rows x 25 columns]

In [7]:
#Get sacved 'data'

with open('/home/gsociety/Desktop/The Model/STORAGE/PREDICT/predictdata.csv', 'a') as file:
    data.to_csv(file, index=False, header=False)

In [8]:
import numpy as np
import pandas as pd   

df1= pd.read_csv('/home/gsociety/Desktop/The Model/STORAGE/PREDICT/predictdata.csv')
df1[-8:]

TC  HOMECODE  AWAYCODE           TIMEr      TIMER  TIMED  \
616   EDINBURGH MADRID        15         1  18/09/08 12:22  Sat 12:22  011:2   
617         PARIS ROME         8         5  18/09/08 12:22  Sat 12:22  011:2   
618   VIENNA AMSTERDAM        13         2  18/09/08 12:22  Sat 12:22  011:2   
619   ATHENS STOCKHOLM        10        11  18/09/08 12:22  Sat 12:22  011:2   
620        LISBON BERN         7        16  18/09/08 12:22  Sat 12:22  011:2   
621    BRUSSELS LONDON         9         4  18/09/08 12:22  Sat 12:22  011:2   
622        OSLO ANKARA         6        14  18/09/08 12:22  Sat 12:22  011:2   
623  BERLIN COPENHAGEN         3        12  18/09/08 12:22  Sat 12:22  011:2   

        1     2     X   HT1   ...     G(0.5)O  G(0.5)U  G(1.5)O  G(1.5)U  \
616  4.85  1.65  4.35  6.00   ...         0.0      0.0     1.22     3.95   
617  2.95  2.25  3.75  3.25   ...         0.0      0.0     0.00     0.00   
618  5.25  1.65  3.95  5.50   ...         0.0      0.0     1.50     2.45   
619  2.05  3.20  4.05  2.55   ...         0.0      0.0     1.25     3.60   
620  1.40  8.25  4.55  1.70   ...         0.0      0.0     1.30     3.10   
621  3.35  2.25  3.25  4.00   ...         0.0      0.0     1.35     3.00   
622  1.40  7.00  5.25  1.90   ...         0.0      0.0     1.20     4.10   
623  1.40  9.75  4.40  1.80   ...         0.0      0.0     1.35     2.85   

     G(2.5)O  G(2.5)U  G(3.5)O  G(3.5)U  G(4.5)O  G(4.5)U  
616     1.65     2.10     2.45     1.50     0.00     0.00  
617     1.65     2.15     2.50     1.45     4.25     1.18  
618     2.40     1.50     4.30     1.18     0.00     0.00  
619     1.70     2.00     2.75     1.40     0.00     0.00  
620     2.05     1.70     3.95     1.20     0.00     0.00  
621     2.30     1.55     4.05     1.20     0.00     0.00  
622     1.65     2.10     2.65     1.40     0.00     0.00  
623     2.30     1.55     3.70     1.22     0.00     0.00  

[8 rows x 25 columns]

In [9]:

#Filter to fit a prediction category

df1= df1[df1['G(2.5)O'] >1.7]

df1= df1[df1['G(2.5)O'] < 1.85]
df1
f=df1.drop_duplicates()
f.head()
f

TC  HOMECODE  AWAYCODE           TIMEr      TIMER  TIMED  \
41        LONDON OSLO         4         6  18/09/08 11:05  Sat 11:05  010:0   
74       PARIS BERLIN         8         3  18/09/08 11:14  Sat 11:14  010:1   
114    EDINBURGH OSLO        15         6  18/09/08 11:19  Sat 11:19  010:1   
115     ATHENS LONDON        10         4  18/09/08 11:19  Sat 11:19  010:1   
385         OSLO BERN         6        16  18/09/08 12:13  Sat 12:13  011:1   
460       ROME LISBON         5         7  18/09/08 12:17  Sat 12:17  011:1   
463  LONDON AMSTERDAM         4         2  18/09/08 12:17  Sat 12:17  011:1   

        1     2     X   HT1   ...     G(0.5)O  G(0.5)U  G(1.5)O  G(1.5)U  \
41   2.10  3.45  3.50  2.40   ...         0.0      0.0     1.25     3.55   
74   4.15  1.95  3.45  4.40   ...         0.0      0.0     1.25     3.50   
114  4.55  1.80  3.55  4.20   ...         0.0      0.0     1.22     3.85   
115  3.60  2.00  3.60  3.30   ...         0.0      0.0     1.20     4.00   
385  1.35  8.00  5.00  1.75   ...         0.0      0.0     1.22     3.80   
460  2.15  3.10  3.80  2.40   ...         0.0      0.0     1.25     3.60   
463  2.10  3.05  4.05  2.40   ...         0.0      0.0     1.18     4.30   

     G(2.5)O  G(2.5)U  G(3.5)O  G(3.5)U  G(4.5)O  G(4.5)U  
41      1.80     1.95     3.05     1.35      0.0      0.0  
74      1.80     1.90     3.05     1.35      0.0      0.0  
114     1.80     1.95     3.10     1.30      0.0      0.0  
115     1.75     1.95     2.95     1.35      0.0      0.0  
385     1.75     1.95     3.25     1.30      0.0      0.0  
460     1.80     1.90     2.95     1.35      0.0      0.0  
463     1.75     2.00     3.15     1.30      0.0      0.0  

[7 rows x 25 columns]

In [10]:
model_cols=['HOMECODE', 'AWAYCODE', '1',
       '2', 'X', 'HT1', 'HT2', 'HTX', 'FS (0:0)', 'FS(0:0)2', 'FS(0:0)X',
       'G(0.5)O', 'G(0.5)U', 'G(1.5)O', 'G(1.5)U', 'G(2.5)O', 'G(2.5)U',
       'G(3.5)O', 'G(3.5)U', 'G(4.5)O', 'G(4.5)U',]

In [11]:

mod_data=f.reindex(columns=model_cols).fillna(0)
####################################

#mod_data
dataR=mod_data.values
dataR

array([[  4.  ,   6.  ,   2.1 ,   3.45,   3.5 ,   2.4 ,   3.75,   2.55,
          1.75,   2.25,  14.5 ,   0.  ,   0.  ,   1.25,   3.55,   1.8 ,
          1.95,   3.05,   1.35,   0.  ,   0.  ],
       [  8.  ,   3.  ,   4.15,   1.95,   3.45,   4.4 ,   2.15,   2.6 ,
          2.6 ,   1.6 ,  12.5 ,   0.  ,   0.  ,   1.25,   3.5 ,   1.8 ,
          1.9 ,   3.05,   1.35,   0.  ,   0.  ],
       [ 15.  ,   6.  ,   4.55,   1.8 ,   3.55,   4.2 ,   2.3 ,   2.45,
          2.55,   1.6 ,  15.75,   0.  ,   0.  ,   1.22,   3.85,   1.8 ,
          1.95,   3.1 ,   1.3 ,   0.  ,   0.  ],
       [ 10.  ,   4.  ,   3.6 ,   2.  ,   3.6 ,   3.3 ,   2.4 ,   2.75,
          2.1 ,   1.8 ,  16.5 ,   0.  ,   0.  ,   1.2 ,   4.  ,   1.75,
          1.95,   2.95,   1.35,   0.  ,   0.  ],
       [  6.  ,  16.  ,   1.35,   8.  ,   5.  ,   1.75,   7.5 ,   2.65,
          1.3 ,   3.8 ,  18.  ,   0.  ,   0.  ,   1.22,   3.8 ,   1.75,
          1.95,   3.25,   1.3 ,   0.  ,   0.  ],
       [  5.  ,   7.  ,   2.15,   3

In [12]:
#Manual Input

p1 =np.array([[  6.  ,  15.  ,   1.4 ,   7.25,   4.75,   1.85,   6.75,   2.5 ,
          1.35,   3.4 ,  16.5 ,   0.  ,   0.  ,   1.3 ,   3.35,   1.8 ,
          1.9 ,   2.85,   1.35,   0.  ,   0.  ],
       [  2.  ,  10.  ,   1.4 ,   7.5 ,   4.7 ,   1.9 ,   6.25,   2.55,
          1.4 ,   3.4 ,  14.  ,   0.  ,   0.  ,   1.25,   3.4 ,   1.8 ,
          1.9 ,   3.1 ,   1.3 ,   0.  ,   0.  ],
       [  5.  ,   3.  ,   2.3 ,   2.65,   4.3 ,   2.65,   2.9 ,   2.8 ,
          1.85,   2.05,  19.25,   0.  ,   0.  ,   1.25,   3.6 ,   1.8 ,
          1.95,   2.85,   1.35,   0.  ,   0.  ],
       [ 10.  ,   4.  ,   3.6 ,   2.1 ,   3.45,   3.35,   2.45,   2.7 ,
          2.15,   1.85,  12.5 ,   0.  ,   0.  ,   1.2 ,   3.95,   1.8 ,
          1.9 ,   3.  ,   1.35,   0.  ,   0.  ],
       [  1.  ,   7.  ,   1.8 ,   3.95,   4.2 ,   2.15,   4.65,   2.5 ,
          1.6 ,   2.6 ,  15.5 ,   0.  ,   0.  ,   1.22,   3.85,   1.75,
          2.  ,   2.95,   1.35,   0.  ,   0.  ],
       [  4.  ,   6.  ,   2.25,   3.45,   3.15,   2.5 ,   3.7 ,   2.45,
          1.85,   2.1 ,  13.75,   0.  ,   0.  ,   1.25,   3.6 ,   1.8 ,
          1.9 ,   2.9 ,   1.35,   0.  ,   0.  ]])

In [13]:
p1=dataR   # Uncomment when manual is used
p1  

array([[  4.  ,   6.  ,   2.1 ,   3.45,   3.5 ,   2.4 ,   3.75,   2.55,
          1.75,   2.25,  14.5 ,   0.  ,   0.  ,   1.25,   3.55,   1.8 ,
          1.95,   3.05,   1.35,   0.  ,   0.  ],
       [  8.  ,   3.  ,   4.15,   1.95,   3.45,   4.4 ,   2.15,   2.6 ,
          2.6 ,   1.6 ,  12.5 ,   0.  ,   0.  ,   1.25,   3.5 ,   1.8 ,
          1.9 ,   3.05,   1.35,   0.  ,   0.  ],
       [ 15.  ,   6.  ,   4.55,   1.8 ,   3.55,   4.2 ,   2.3 ,   2.45,
          2.55,   1.6 ,  15.75,   0.  ,   0.  ,   1.22,   3.85,   1.8 ,
          1.95,   3.1 ,   1.3 ,   0.  ,   0.  ],
       [ 10.  ,   4.  ,   3.6 ,   2.  ,   3.6 ,   3.3 ,   2.4 ,   2.75,
          2.1 ,   1.8 ,  16.5 ,   0.  ,   0.  ,   1.2 ,   4.  ,   1.75,
          1.95,   2.95,   1.35,   0.  ,   0.  ],
       [  6.  ,  16.  ,   1.35,   8.  ,   5.  ,   1.75,   7.5 ,   2.65,
          1.3 ,   3.8 ,  18.  ,   0.  ,   0.  ,   1.22,   3.8 ,   1.75,
          1.95,   3.25,   1.3 ,   0.  ,   0.  ],
       [  5.  ,   7.  ,   2.15,   3

In [14]:
X_predict = p1.reshape(p1.shape[0], 21)
X_predict = p1.astype('float32')
X_predict /= 25


pp=X_predict
pp.shape
pp

array([[ 0.16      ,  0.23999999,  0.084     ,  0.138     ,  0.14      ,
         0.096     ,  0.15000001,  0.102     ,  0.07      ,  0.09      ,
         0.57999998,  0.        ,  0.        ,  0.05      ,  0.142     ,
         0.072     ,  0.078     ,  0.122     ,  0.054     ,  0.        ,
         0.        ],
       [ 0.31999999,  0.12      ,  0.16600001,  0.078     ,  0.138     ,
         0.176     ,  0.086     ,  0.10399999,  0.10399999,  0.064     ,
         0.5       ,  0.        ,  0.        ,  0.05      ,  0.14      ,
         0.072     ,  0.076     ,  0.122     ,  0.054     ,  0.        ,
         0.        ],
       [ 0.60000002,  0.23999999,  0.18200001,  0.072     ,  0.142     ,
         0.168     ,  0.092     ,  0.098     ,  0.102     ,  0.064     ,
         0.63      ,  0.        ,  0.        ,  0.0488    ,  0.154     ,
         0.072     ,  0.078     ,  0.124     ,  0.052     ,  0.        ,
         0.        ],
       [ 0.40000001,  0.16      ,  0.14399999,  0.08      

In [15]:
#Loadd Preditio Model

In [16]:
from keras.models import load_model
import numpy as np
#model = load_model('g1_model.h5')
model = load_model('d642857modelGS.h5') ##Keep this MODEL_Magic begins begin=55 end=45

#model = load_model('d_U476190479029model_s.h5') ##Keep this MODEL_Magic begins begin=55 end=45

#model = load_model('model-01.h5')

Using TensorFlow backend.


In [17]:
p_propability = model.predict(pp)
p_class=model.predict_classes(pp)

In [18]:
p_propability

array([[ 0.42521873,  0.5747813 ],
       [ 0.39620882,  0.60379118],
       [ 0.45841578,  0.54158425],
       [ 0.42246839,  0.57753158],
       [ 0.56027037,  0.43972957],
       [ 0.45704475,  0.54295522],
       [ 0.45212293,  0.54787713]], dtype=float32)

In [19]:
p_class

array([1, 1, 1, 1, 0, 1, 1])

In [29]:
f.iloc[[0,], [0, 4,5,6,7,8]]

TC      TIMER  TIMED    1     2    X
41  LONDON OSLO  Sat 11:05  010:0  2.1  3.45  3.5

In [39]:
f.iloc[:, 3:17][f.X > 3]  #Very important

TIMEr      TIMER  TIMED     1     2     X   HT1   HT2   HTX  \
41   18/09/08 11:05  Sat 11:05  010:0  2.10  3.45  3.50  2.40  3.75  2.55   
74   18/09/08 11:14  Sat 11:14  010:1  4.15  1.95  3.45  4.40  2.15  2.60   
114  18/09/08 11:19  Sat 11:19  010:1  4.55  1.80  3.55  4.20  2.30  2.45   
115  18/09/08 11:19  Sat 11:19  010:1  3.60  2.00  3.60  3.30  2.40  2.75   
385  18/09/08 12:13  Sat 12:13  011:1  1.35  8.00  5.00  1.75  7.50  2.65   
460  18/09/08 12:17  Sat 12:17  011:1  2.15  3.10  3.80  2.40  3.30  2.75   
463  18/09/08 12:17  Sat 12:17  011:1  2.10  3.05  4.05  2.40  3.45  2.65   

     FS (0:0)  FS(0:0)2  FS(0:0)X  G(0.5)O  G(0.5)U  
41       1.75      2.25     14.50      0.0      0.0  
74       2.60      1.60     12.50      0.0      0.0  
114      2.55      1.60     15.75      0.0      0.0  
115      2.10      1.80     16.50      0.0      0.0  
385      1.30      3.80     18.00      0.0      0.0  
460      1.80      2.10     17.75      0.0      0.0  
463      1.65      2.25     28.00      0.0      0.0